-- R5a (audyt wyszukiwarki R1+R2): polskie nazwy i aliasy potoczne ćwiczeń.
-- Słownik zatwierdzony przez właściciela 2026-07-17 (docs/r5a-slownik-pl-propozycja.md).
-- Dane są zgodne ze scripts/seed.ts — oba czytają scripts/data/exercise-names-pl.json.

alter table public.exercises add column if not exists name_pl text;
alter table public.exercises add column if not exists search_aliases text[] not null default '{}';

-- Migracja danych z guardem na pusty stan (wzorzec 20260716141007): na świeżej
-- bazie CI ćwiczenia powstają dopiero w kroku seeda, który sam wypełnia kolumny.
do $tag$
begin
  if not exists (select 1 from public.exercises) then
    raise notice 'Pomijam nazwy PL: baza referencyjna jest jeszcze pusta.';
    return;
  end if;

  update public.exercises e
  set name_pl = v.name_pl,
      search_aliases = v.aliases
  from (values
    ('Ab_Wheel_Rollout', 'Rozwijanie kółka (ab wheel)', array['kółko']::text[]),
    ('Alternate_Hammer_Curl', 'Uginanie młotkowe naprzemiennie', '{}'::text[]),
    ('Alternating_Renegade_Row', 'Wiosłowanie w podporze (renegade row)', '{}'::text[]),
    ('Arnold_Dumbbell_Press', 'Wyciskanie Arnolda', array['arnoldki']::text[]),
    ('Band_Lat_Pulldown', 'Ściąganie gumy szerokim chwytem', '{}'::text[]),
    ('Barbell_Bench_Press_-_Medium_Grip', 'Wyciskanie sztangi na ławce płaskiej', array['ławka','wyciskanie leżąc','bench']::text[]),
    ('Barbell_Curl', 'Uginanie ramion ze sztangą', '{}'::text[]),
    ('Barbell_Deadlift', 'Martwy ciąg klasyczny', array['martwy','martwy ciąg']::text[]),
    ('Barbell_Full_Squat', 'Przysiad pełny ze sztangą', '{}'::text[]),
    ('Barbell_Glute_Bridge', 'Mostek biodrowy ze sztangą', array['mostek']::text[]),
    ('Barbell_Hack_Squat', 'Przysiad hack ze sztangą', '{}'::text[]),
    ('Barbell_Hip_Thrust', 'Hip thrust ze sztangą', array['hip thrust','biodra']::text[]),
    ('Barbell_Incline_Bench_Press_-_Medium_Grip', 'Wyciskanie sztangi na ławce skośnej', array['skos','ławka skośna']::text[]),
    ('Barbell_Lunge', 'Wykroki ze sztangą', '{}'::text[]),
    ('Barbell_Seated_Calf_Raise', 'Wspięcia siedząc ze sztangą', '{}'::text[]),
    ('Barbell_Shoulder_Press', 'Wyciskanie sztangi nad głowę siedząc', '{}'::text[]),
    ('Barbell_Shrug', 'Unoszenie barków ze sztangą (szrugsy)', array['szrugsy']::text[]),
    ('Barbell_Squat', 'Przysiad ze sztangą', array['przysiad','przysiady','squat']::text[]),
    ('Barbell_Walking_Lunge', 'Wykroki chodzone ze sztangą', '{}'::text[]),
    ('Bench_Dips', 'Pompki tricepsowe tyłem na ławce', '{}'::text[]),
    ('Bent_Over_Barbell_Row', 'Wiosłowanie sztangą w opadzie', array['wiosłowanie']::text[]),
    ('Bent_Over_Two-Dumbbell_Row', 'Wiosłowanie hantlami w opadzie', '{}'::text[]),
    ('Body_Tricep_Press', 'Bodyweight skullcrusher (przy ławce)', '{}'::text[]),
    ('Bodyweight_Squat', 'Przysiad bez obciążenia', '{}'::text[]),
    ('Bodyweight_Walking_Lunge', 'Wykroki chodzone bez obciążenia', '{}'::text[]),
    ('Box_Squat', 'Przysiad na skrzynię', '{}'::text[]),
    ('Bulgarian_Split_Squat', 'Przysiad bułgarski', array['bułgar','bułgary']::text[]),
    ('Butterfly', 'Maszyna motylkowa (pec deck)', array['motylek','pec deck']::text[]),
    ('Cable_Chest_Press', 'Wyciskanie na wyciągu (klatka)', '{}'::text[]),
    ('Cable_Crossover', 'Krzyżowanie linek wyciągu (brama)', array['brama','krzyżowanie']::text[]),
    ('Cable_Crunch', 'Spięcia brzucha na wyciągu w klęku', array['allahy']::text[]),
    ('Cable_Hammer_Curls_-_Rope_Attachment', 'Uginanie młotkowe na wyciągu (lina)', '{}'::text[]),
    ('Cable_Hip_Adduction', 'Przywodzenie nogi na wyciągu', '{}'::text[]),
    ('Cable_Incline_Triceps_Extension', 'Prostowanie ramion na wyciągu w skosie', '{}'::text[]),
    ('Cable_Lying_Triceps_Extension', 'Wyciskanie francuskie na wyciągu leżąc', '{}'::text[]),
    ('Cable_One_Arm_Tricep_Extension', 'Prostowanie ramienia na wyciągu jednorącz', '{}'::text[]),
    ('Cable_Preacher_Curl', 'Uginanie na modlitewniku na wyciągu', '{}'::text[]),
    ('Cable_Rear_Delt_Fly', 'Odwrotne rozpiętki na wyciągu', '{}'::text[]),
    ('Cable_Reverse_Crunch', 'Odwrotne spięcia na wyciągu', '{}'::text[]),
    ('Cable_Rope_Overhead_Triceps_Extension', 'Prostowanie ramion zza głowy na wyciągu (lina)', '{}'::text[]),
    ('Cable_Russian_Twists', 'Skręty rosyjskie na wyciągu', '{}'::text[]),
    ('Cable_Seated_Crunch', 'Spięcia brzucha na wyciągu siedząc', '{}'::text[]),
    ('Cable_Seated_Lateral_Raise', 'Wznosy bokiem na wyciągu siedząc', '{}'::text[]),
    ('Cable_Shrugs', 'Unoszenie barków na wyciągu', '{}'::text[]),
    ('Cable_Wrist_Curl', 'Uginanie nadgarstków na wyciągu', '{}'::text[]),
    ('Calf_Press', 'Wspięcia na palce na maszynie (calf press)', '{}'::text[]),
    ('Calf_Press_On_The_Leg_Press_Machine', 'Wspięcia na suwnicy (leg press)', '{}'::text[]),
    ('Calf_Raise_On_A_Dumbbell', 'Wspięcia na palce na hantlu', array['łydki','wspięcia']::text[]),
    ('Chest-Supported_Dumbbell_Row', 'Wiosłowanie hantlami z klatką opartą o ławkę', '{}'::text[]),
    ('Chin-Up', 'Podciąganie podchwytem', '{}'::text[]),
    ('Close-Grip_Barbell_Bench_Press', 'Wyciskanie sztangi wąskim chwytem', '{}'::text[]),
    ('Close-Grip_Dumbbell_Press', 'Wyciskanie hantli wąsko (chwyt neutralny)', '{}'::text[]),
    ('Close-Grip_EZ_Bar_Curl', 'Uginanie sztangą łamaną wąskim chwytem', '{}'::text[]),
    ('Close-Grip_Front_Lat_Pulldown', 'Ściąganie drążka wyciągu wąskim chwytem', '{}'::text[]),
    ('Concentration_Curls', 'Uginanie koncentracyjne hantlem', '{}'::text[]),
    ('Copenhagen_Plank', 'Deska kopenhaska', array['kopenhaga']::text[]),
    ('Cross_Body_Hammer_Curl', 'Uginanie młotkowe skośne (cross body)', '{}'::text[]),
    ('Cross-Body_Crunch', 'Brzuszki skrętne (łokieć do kolana)', '{}'::text[]),
    ('Crunches', 'Brzuszki (spięcia)', array['brzuszki']::text[]),
    ('Curtsy_Lunge', 'Zakroki skrzyżne (curtsy)', '{}'::text[]),
    ('Dead_Bug', 'Dead bug', array['deadbug']::text[]),
    ('Decline_Barbell_Bench_Press', 'Wyciskanie sztangi głową w dół', '{}'::text[]),
    ('Decline_Dumbbell_Bench_Press', 'Wyciskanie hantli głową w dół', '{}'::text[]),
    ('Decline_Dumbbell_Flyes', 'Rozpiętki z hantlami głową w dół', '{}'::text[]),
    ('Decline_Dumbbell_Triceps_Extension', 'Wyciskanie francuskie hantlami głową w dół', '{}'::text[]),
    ('Decline_Push-Up', 'Pompki głową w dół', '{}'::text[]),
    ('Dip_Machine', 'Dipy na maszynie', '{}'::text[]),
    ('Dips_-_Chest_Version', 'Pompki na poręczach (klatka)', '{}'::text[]),
    ('Dips_-_Triceps_Version', 'Pompki na poręczach (triceps)', array['dipy','poręcze']::text[]),
    ('Drag_Curl', 'Uginanie ze sztangą wzdłuż tułowia (drag curl)', '{}'::text[]),
    ('Dumbbell_Alternate_Bicep_Curl', 'Uginanie ramion z hantlami naprzemiennie', '{}'::text[]),
    ('Dumbbell_Bench_Press', 'Wyciskanie hantli na ławce płaskiej', '{}'::text[]),
    ('Dumbbell_Bench_Press_with_Neutral_Grip', 'Wyciskanie hantli chwytem neutralnym', '{}'::text[]),
    ('Dumbbell_Bicep_Curl', 'Uginanie ramion z hantlami', array['biceps','uginanie']::text[]),
    ('Dumbbell_Floor_Press', 'Wyciskanie hantli leżąc na podłodze', '{}'::text[]),
    ('Dumbbell_Flyes', 'Rozpiętki z hantlami', array['rozpiętki']::text[]),
    ('Dumbbell_Hip_Thrust', 'Hip thrust z hantlem', array['hip thrust','biodra']::text[]),
    ('Dumbbell_Lunges', 'Wykroki z hantlami', array['wykroki']::text[]),
    ('Dumbbell_One-Arm_Shoulder_Press', 'Wyciskanie hantla nad głowę jednorącz', '{}'::text[]),
    ('Dumbbell_Rear_Lunge', 'Zakroki z hantlami', array['zakroki']::text[]),
    ('Dumbbell_Seated_One-Leg_Calf_Raise', 'Wspięcia siedząc jednonóż z hantlem', '{}'::text[]),
    ('Dumbbell_Shoulder_Press', 'Wyciskanie hantli nad głowę', '{}'::text[]),
    ('Dumbbell_Shrug', 'Unoszenie barków z hantlami (szrugsy)', array['szrugsy']::text[]),
    ('Dumbbell_Squat', 'Przysiad z hantlami', '{}'::text[]),
    ('Dumbbell_Squat_To_A_Bench', 'Przysiad z hantlami na ławkę', '{}'::text[]),
    ('Dumbbell_Step_Ups', 'Wejścia na skrzynię z hantlami', '{}'::text[]),
    ('Elevated_Back_Lunge', 'Zakroki z podwyższenia', '{}'::text[]),
    ('EZ-Bar_Curl', 'Uginanie ramion sztangą łamaną', '{}'::text[]),
    ('EZ-Bar_Skullcrusher', 'Wyciskanie francuskie sztangą łamaną leżąc', array['francuskie','francuz']::text[]),
    ('Face_Pull', 'Face pull', array['facepull']::text[]),
    ('Farmers_Walk', 'Spacer farmera', array['farmerki','spacer farmera']::text[]),
    ('Flat_Bench_Lying_Leg_Raise', 'Unoszenie nóg leżąc na ławce', '{}'::text[]),
    ('Floor_Press', 'Wyciskanie sztangi leżąc na podłodze', '{}'::text[]),
    ('Freehand_Jump_Squat', 'Przysiad z wyskokiem', '{}'::text[]),
    ('Front_Barbell_Squat', 'Przysiad przedni ze sztangą', '{}'::text[]),
    ('Front_Cable_Raise', 'Wznosy przodem na wyciągu', '{}'::text[]),
    ('Front_Dumbbell_Raise', 'Wznosy hantli przodem', '{}'::text[]),
    ('Front_Incline_Dumbbell_Raise', 'Wznosy przodem na ławce skośnej', '{}'::text[]),
    ('Front_Two-Dumbbell_Raise', 'Wznosy przodem oburącz', '{}'::text[]),
    ('Full_Range-Of-Motion_Lat_Pulldown', 'Ściąganie drążka pełnym zakresem', '{}'::text[]),
    ('Glute_Ham_Raise', 'Glute ham raise (GHD)', array['ghr']::text[]),
    ('Glute_Kickback', 'Odmachy nogi w klęku', '{}'::text[]),
    ('Goblet_Squat', 'Przysiad goblet', array['goblet']::text[]),
    ('Good_Morning', 'Skłony dzień dobry (good morning)', array['dzień dobry']::text[]),
    ('Hack_Squat', 'Przysiad na suwnicy hack', array['hack','hacki']::text[]),
    ('Hammer_Curls', 'Uginanie ramion chwytem młotkowym', array['młotki']::text[]),
    ('Hammer_Grip_Incline_DB_Bench_Press', 'Wyciskanie hantli chwytem neutralnym na skosie', '{}'::text[]),
    ('Handstand_Push-Ups', 'Pompki w staniu na rękach', '{}'::text[]),
    ('Hanging_Knee_Raise', 'Unoszenie kolan w zwisie', '{}'::text[]),
    ('Hanging_Leg_Raise', 'Unoszenie nóg w zwisie', array['unoszenie nóg']::text[]),
    ('High_Cable_Curls', 'Uginanie ramion na górnym wyciągu', '{}'::text[]),
    ('Hollow_Body_Hold', 'Hollow body hold', array['hollow']::text[]),
    ('Hyperextensions_Back_Extensions', 'Skłony rzymskie (hyperextensions)', array['rzymka','skłony rzymskie']::text[]),
    ('Incline_Dumbbell_Curl', 'Uginanie ramion z hantlami na ławce skośnej', '{}'::text[]),
    ('Incline_Dumbbell_Flyes', 'Rozpiętki z hantlami na ławce skośnej', '{}'::text[]),
    ('Incline_Dumbbell_Press', 'Wyciskanie hantli na ławce skośnej', array['skos','ławka skośna']::text[]),
    ('Incline_Hammer_Curls', 'Uginanie młotkowe na ławce skośnej', '{}'::text[]),
    ('Inverted_Row', 'Wiosłowanie w podporze (australijskie)', array['australijskie']::text[]),
    ('Jackknife_Sit-Up', 'Scyzoryki', '{}'::text[]),
    ('Kettlebell_One-Legged_Deadlift', 'Martwy ciąg jednonóż z kettlebell', '{}'::text[]),
    ('Kettlebell_Swing', 'Wymachy kettlebell (swing)', array['swing']::text[]),
    ('Kneeling_High_Pulley_Row', 'Wiosłowanie górnego wyciągu w klęku', '{}'::text[]),
    ('L-Sit_Hold', 'L-sit', '{}'::text[]),
    ('Landmine_Press', 'Wyciskanie landmine', '{}'::text[]),
    ('Leg_Extensions', 'Prostowanie nóg siedząc (maszyna)', array['prostowanie nóg']::text[]),
    ('Leg_Press', 'Wyciskanie nogami (leg press)', array['leg press','nogi maszyna']::text[]),
    ('Leverage_Chest_Press', 'Wyciskanie na maszynie (chest press)', '{}'::text[]),
    ('Leverage_High_Row', 'Wiosłowanie na maszynie z góry (high row)', '{}'::text[]),
    ('Leverage_Incline_Chest_Press', 'Wyciskanie na maszynie w skosie', '{}'::text[]),
    ('Leverage_Iso_Row', 'Wiosłowanie na maszynie', '{}'::text[]),
    ('Low_Cable_Crossover', 'Krzyżowanie linek z dołu (brama)', '{}'::text[]),
    ('Lying_Dumbbell_Tricep_Extension', 'Wyciskanie francuskie hantlami leżąc', array['francuskie','francuz']::text[]),
    ('Lying_Leg_Curls', 'Uginanie nóg leżąc (maszyna)', array['uginanie nóg']::text[]),
    ('Lying_T-Bar_Row', 'Wiosłowanie T-bar z klatką opartą', '{}'::text[]),
    ('Machine_Bench_Press', 'Wyciskanie na maszynie leżąc', '{}'::text[]),
    ('Machine_Hip_Abduction', 'Odwodzenie bioder na maszynie', '{}'::text[]),
    ('Machine_Preacher_Curls', 'Uginanie ramion na maszynie (modlitewnik)', '{}'::text[]),
    ('Machine_Shoulder_Military_Press', 'Wyciskanie nad głowę na maszynie', '{}'::text[]),
    ('Mountain_Climbers', 'Mountain climbers', '{}'::text[]),
    ('Narrow_Stance_Hack_Squats', 'Przysiad hack wąsko', '{}'::text[]),
    ('Natural_Glute_Ham_Raise', 'Glute ham raise bez maszyny', array['ghr']::text[]),
    ('Nordic_Hamstring_Curl', 'Nordic curl', array['nordiki','nordic']::text[]),
    ('Oblique_Crunches', 'Brzuszki skośne', '{}'::text[]),
    ('One_Arm_Dumbbell_Preacher_Curl', 'Uginanie na modlitewniku jednorącz', '{}'::text[]),
    ('One_Arm_Lat_Pulldown', 'Ściąganie wyciągu jednorącz', '{}'::text[]),
    ('One-Arm_Dumbbell_Row', 'Wiosłowanie hantlem jednorącz', array['wiosło hantlem']::text[]),
    ('One-Arm_Kettlebell_Swings', 'Wymachy kettlebell jednorącz', '{}'::text[]),
    ('One-Legged_Cable_Kickback', 'Odmachy nogi na wyciągu', '{}'::text[]),
    ('Overhead_Cable_Triceps_Extension', 'Prostowanie ramion na wyciągu zza głowy', '{}'::text[]),
    ('Pallof_Press', 'Pallof press', '{}'::text[]),
    ('Palms-Down_Wrist_Curl_Over_A_Bench', 'Uginanie nadgarstków nachwytem na ławce', '{}'::text[]),
    ('Palms-Up_Barbell_Wrist_Curl_Over_A_Bench', 'Uginanie nadgarstków podchwytem na ławce', '{}'::text[]),
    ('Pendlay_Row', 'Wiosłowanie Pendlaya', '{}'::text[]),
    ('Pike_Push-Up', 'Pompki pike', '{}'::text[]),
    ('Plank', 'Deska (plank)', array['deska','plank']::text[]),
    ('Plie_Dumbbell_Squat', 'Przysiad sumo z hantlem', '{}'::text[]),
    ('Preacher_Curl', 'Uginanie ramion na modlitewniku', array['modlitewnik']::text[]),
    ('Pull_Through', 'Pull through (przyciąganie liny między nogami)', '{}'::text[]),
    ('Pullups', 'Podciąganie nachwytem', array['podciąganie','drążek']::text[]),
    ('Push_Press', 'Push press', '{}'::text[]),
    ('Push-Ups_-_Close_Triceps_Position', 'Pompki wąskie (tricepsowe)', '{}'::text[]),
    ('Push-Ups_With_Feet_Elevated', 'Pompki z nogami na podwyższeniu', '{}'::text[]),
    ('Pushups', 'Pompki', array['pompki']::text[]),
    ('Reverse_Flyes', 'Odwrotne rozpiętki', '{}'::text[]),
    ('Reverse_Hyperextension', 'Odwrotne skłony rzymskie', '{}'::text[]),
    ('Reverse_Machine_Flyes', 'Odwrotne rozpiętki na maszynie', '{}'::text[]),
    ('Reverse_Nordic_Curl', 'Odwrotny nordic curl', '{}'::text[]),
    ('Romanian_Deadlift', 'Martwy ciąg rumuński', array['rumuński','rumun','rdl']::text[]),
    ('Rope_Crunch', 'Spięcia brzucha z liną wyciągu', '{}'::text[]),
    ('Russian_Twist', 'Skręty rosyjskie', '{}'::text[]),
    ('Scapular_Pull-Up', 'Podciąganie łopatkowe', '{}'::text[]),
    ('Seated_Cable_Rows', 'Wiosłowanie na wyciągu siedząc', '{}'::text[]),
    ('Seated_Calf_Raise', 'Wspięcia na palce siedząc (maszyna)', '{}'::text[]),
    ('Seated_Dumbbell_Press', 'Wyciskanie hantli siedząc', '{}'::text[]),
    ('Seated_Good_Mornings', 'Skłony dzień dobry siedząc', '{}'::text[]),
    ('Seated_Leg_Curl', 'Uginanie nóg siedząc (maszyna)', '{}'::text[]),
    ('Side_Lateral_Raise', 'Wznosy hantli bokiem', array['wznosy']::text[]),
    ('Single_Leg_Calf_Raise', 'Wspięcia na palce jednonóż', '{}'::text[]),
    ('Single_Leg_Glute_Bridge', 'Mostek biodrowy jednonóż', array['mostek']::text[]),
    ('Single-Arm_Push-Up', 'Pompka jednorącz', '{}'::text[]),
    ('Single-Leg_Hip_Thrust', 'Hip thrust jednonóż', '{}'::text[]),
    ('Sit-Up', 'Brzuszki pełne (sit-up)', '{}'::text[]),
    ('Smith_Machine_Bench_Press', 'Wyciskanie na suwnicy Smitha', '{}'::text[]),
    ('Smith_Machine_Bent_Over_Row', 'Wiosłowanie na suwnicy Smitha', '{}'::text[]),
    ('Smith_Machine_Close-Grip_Bench_Press', 'Wyciskanie wąsko na suwnicy Smitha', '{}'::text[]),
    ('Smith_Machine_Incline_Bench_Press', 'Wyciskanie na suwnicy Smitha na ławce skośnej', '{}'::text[]),
    ('Smith_Machine_Squat', 'Przysiad na suwnicy Smitha', array['suwnica smitha','smith']::text[]),
    ('Smith_Machine_Stiff-Legged_Deadlift', 'Martwy ciąg na prostych nogach na suwnicy Smitha', '{}'::text[]),
    ('Split_Squat_with_Dumbbells', 'Przysiad rozdzielny z hantlami', '{}'::text[]),
    ('Split_Squats', 'Przysiad rozdzielny (split squat)', '{}'::text[]),
    ('Standing_Biceps_Cable_Curl', 'Uginanie ramion na wyciągu', '{}'::text[]),
    ('Standing_Calf_Raises', 'Wspięcia na palce stojąc (maszyna)', array['łydki','wspięcia']::text[]),
    ('Standing_Dumbbell_Press', 'Wyciskanie hantli nad głowę stojąc', '{}'::text[]),
    ('Standing_Dumbbell_Triceps_Extension', 'Wyciskanie francuskie hantlem stojąc', '{}'::text[]),
    ('Standing_Dumbbell_Upright_Row', 'Podciąganie hantli wzdłuż tułowia', '{}'::text[]),
    ('Standing_Military_Press', 'Wyciskanie żołnierskie (OHP)', array['ohp','military','żołnierskie']::text[]),
    ('Step-up_with_Knee_Raise', 'Wejście na skrzynię z unoszeniem kolana', '{}'::text[]),
    ('Stiff-Legged_Dumbbell_Deadlift', 'Martwy ciąg na prostych nogach z hantlami', '{}'::text[]),
    ('Straight-Arm_Dumbbell_Pullover', 'Przenoszenie hantla za głowę (pullover)', '{}'::text[]),
    ('Straight-Arm_Pulldown', 'Ściąganie wyciągu prostymi ramionami', '{}'::text[]),
    ('Sumo_Deadlift', 'Martwy ciąg sumo', array['sumo']::text[]),
    ('Superman', 'Superman (unoszenie rąk i nóg leżąc)', '{}'::text[]),
    ('T-Bar_Row_with_Handle', 'Wiosłowanie sztangą T (T-bar)', array['t-bar']::text[]),
    ('Thigh_Abductor', 'Odwodzenie nóg na maszynie', array['odwodzenie']::text[]),
    ('Thigh_Adductor', 'Przywodzenie nóg na maszynie', array['przywodzenie']::text[]),
    ('Tibialis_Raise', 'Unoszenie palców stóp (tibialis)', '{}'::text[]),
    ('Triceps_Pushdown', 'Prostowanie ramion na wyciągu', array['triceps linka','pushdown']::text[]),
    ('Underhand_Cable_Pulldowns', 'Ściąganie drążka podchwytem', '{}'::text[]),
    ('Upright_Barbell_Row', 'Podciąganie sztangi wzdłuż tułowia', '{}'::text[]),
    ('Upright_Cable_Row', 'Podciąganie linki wzdłuż tułowia', '{}'::text[]),
    ('V-Bar_Pullup', 'Podciąganie chwytem neutralnym (V-bar)', '{}'::text[]),
    ('Weighted_Crunches', 'Brzuszki z obciążeniem', '{}'::text[]),
    ('Wide-Grip_Lat_Pulldown', 'Ściąganie drążka wyciągu szerokim chwytem', array['ściąganie drążka','lat pulldown']::text[])
  ) as v(id, name_pl, aliases)
  where e.id = v.id;
end
$tag$;
